name: Build and publish docker image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
        
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: build artifacts
        run: |
          mvn -version
          mvn install

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/bungeekick-*
          draft: false
          prerelease: false
          tag_name: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
